from fastapi import APIRouter, Depends, HTTPException
from sqlalchemy.orm import Session, joinedload
from app.database import get_db
from app.models import Transaction, Order
from app.schemas import TransactionCreate, TransactionRead
from datetime import datetime
from typing import Optional
from app.auth import get_current_user

router = APIRouter(
    prefix="/transactions",
    tags=["transactions"],
    dependencies=[Depends(get_current_user)]
)

def calculate_cost(transaction: TransactionCreate):
    queried_cost = 0
    for order_item in transaction.orders:
        queried_cost += order_item.quantity * order_item.order_cost
    return queried_cost

@router.post("", response_model=TransactionRead)
def create_transaction(transaction: TransactionCreate, db: Session = Depends(get_db)):
    
    queried_cost = calculate_cost(transaction)

    #create a row object. similar to values(column = value, column2 = value)
    db_transaction = Transaction(created_at=transaction.created_at, total_cost=queried_cost)

    #insert into transactions
    db.add(db_transaction)

    #since id is generated by db and not the user, fetch it from the db.
    #insert but not commit. useful for generating serial ids
    db.flush()

    #now we can populate the orders table too since we have the transaction_id now
    #list comprehension. creating a list of row object to be added
    orders = [Order(transaction_id=db_transaction.transaction_id, service_id=order_item.service_id, motor_id=order_item.motor_id, order_cost = order_item.order_cost, quantity=order_item.quantity)
              for order_item in transaction.orders]
    
    #insert into orders
    db.add_all(orders)

    #commit
    db.commit()

    #get the latest row data from the db, not in memory.
    db.refresh(db_transaction)
    
    #return something to the client
    return db_transaction

@router.get("", response_model=list[TransactionRead])
def get_transactions(
    start_date: Optional[datetime] = None,
    end_date: Optional[datetime] = None,
    db: Session = Depends(get_db)
):
    #query all transactions
    query = db.query(Transaction).options(
        joinedload(Transaction.orders).joinedload(Order.service),
        joinedload(Transaction.orders).joinedload(Order.motor)
    )
    
    if start_date:
        query = query.filter(Transaction.created_at >= start_date)
    if end_date:
        query = query.filter(Transaction.created_at <= end_date)
        
    db_transactions = query.all()
    
    return db_transactions

@router.get("/{id}", response_model=TransactionRead)
def get_transaction(id: int, db: Session = Depends(get_db)):
    #query transactions but filtering transaction_id by id
    db_transaction = db.query(Transaction).filter(Transaction.transaction_id == id).options(
        joinedload(Transaction.orders).joinedload(Order.service),
        joinedload(Transaction.orders).joinedload(Order.motor)
    ).first()
    if db_transaction is None:
        raise HTTPException(status_code=404, detail=f'Transaction {id} does not exist!')
    return db_transaction

@router.put("/{id}", response_model=TransactionRead)
def update_transaction(id: int, transaction: TransactionCreate, db: Session = Depends(get_db)):

    db_transaction = db.query(Transaction).filter(Transaction.transaction_id == id).first()

    if db_transaction is None:
        raise HTTPException(status_code=404, detail=f'Transaction {id} does not exist!')

    db_transaction.created_at = transaction.created_at

    db.query(Order).filter(Order.transaction_id == id).delete()
    
    #recalculate the cost
    queried_cost = calculate_cost(transaction)
    #reinserting orders again
    orders = [Order(transaction_id=db_transaction.transaction_id, service_id=order_item.service_id, motor_id=order_item.motor_id, order_cost = order_item.order_cost ,quantity=order_item.quantity) for order_item in transaction.orders]
    
    db.add_all(orders)    

    db_transaction.total_cost = queried_cost

    db.commit()
    db.refresh(db_transaction)
    return db_transaction

@router.delete("/{id}")
def delete_transaction(id: int, db: Session = Depends(get_db)):
    query = db.query(Transaction).filter(Transaction.transaction_id == id).first()
    if query is None:
        raise HTTPException(status_code=404, detail=f"Transaction {id} doesn't exist!")
    db.delete(query)
    db.commit()
    return {"message": f"Transaction {id} deleted succesfully"}
